# Generated by Django 4.2.13 on 2024-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
