# Generated by Django 4.2.13 on 2024-08-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=15,
            ),
        ),
    ]
