# Generated by Django 4.2.13 on 2024-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_fitnessblogpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
