# Generated by Django 4.2.13 on 2024-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessblogpost",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
