# Generated by Django 4.2.13 on 2024-10-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_fitnessblogpost_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessblogpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
