# Generated by Django 4.2.13 on 2024-11-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_workoutcategories_fitnessexercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="equipment_images/")),
                ("amazon_link", models.URLField()),
            ],
        ),
    ]
