# Generated by Django 4.2.13 on 2024-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_cancellationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiprequest",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
