# Generated by Django 4.2.13 on 2024-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_membershiprequest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
